wandb_version: 1

bagging_temperature:
  desc: null
  value: 0.30015754031661007
l2_leaf_reg:
  desc: null
  value: 18
learning_rate:
  desc: null
  value: 0.04335738060100423
max_depth:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.6
    framework: catboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690292508.681543
    t:
      1:
      - 5
      - 7
      - 53
      - 55
      - 89
      2:
      - 5
      - 7
      - 53
      - 55
      - 89
      3:
      - 2
      - 23
      - 27
      - 37
      4: 3.10.9
      5: 0.15.6
      8:
      - 5
