wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.3
    framework: catboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689953208.675458
    t:
      1:
      - 2
      - 3
      - 5
      - 6
      - 7
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 6
      - 7
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.10.9
      5: 0.15.3
      8:
      - 5
