wandb_version: 1

bagging_temperature:
  desc: null
  value: 0.4022323147659861
l2_leaf_reg:
  desc: null
  value: 7
learning_rate:
  desc: null
  value: 0.04416147477351095
max_depth:
  desc: null
  value: 7
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.3
    framework: catboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689951140.299315
    t:
      1:
      - 2
      - 3
      - 5
      - 6
      - 7
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 6
      - 7
      - 53
      - 55
      3:
      - 2
      - 23
      - 27
      - 37
      4: 3.10.9
      5: 0.15.3
      8:
      - 5
