wandb_version: 1

bagging_temperature:
  desc: null
  value: 0.0806264786368231
l2_leaf_reg:
  desc: null
  value: 81
learning_rate:
  desc: null
  value: 0.08363096315252286
max_depth:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.6
    framework: catboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690255052.394418
    t:
      1:
      - 5
      - 7
      - 53
      - 55
      - 89
      2:
      - 5
      - 7
      - 53
      - 55
      - 89
      3:
      - 2
      - 23
      - 27
      - 37
      4: 3.10.9
      5: 0.15.6
      8:
      - 5
