apiVersion: 1



datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db.:5432
    database: evidently_metrics
    user: postgres
    secureJsonData:
      password: 'example'
    jsonData:
      sslmode: 'disable'
