name: CI-Tests
on:
    pull_request:
        branches:
            - 'main'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.10.9
              uses: actions/setup-python@v4
              with:
                    python-version: 3.10.9

            - name: Install dependencies
              run: pip install pipenv && pipenv install && pipenv install --dev && pip install pandas

            - name: Run Unit tests
              run: pipenv run pytest unit_tests/

            - name: Lint
              run: pipenv run pylint --recursive=y .

            - name: Integration Test
              working-directory: 'integration_tests/'
              run: |
                . run.sh
